CREATE TABLE public.Families (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  parent_guardian_first_name_1 TEXT NOT NULL DEFAULT 'NOT NULL'::TEXT,
  parent_guardian_last_name_1 TEXT NOT NULL DEFAULT 'NOT NULL'::TEXT,
  parent_guardian_first_name_2 TEXT NULL DEFAULT ''::TEXT,
  parent_guardian_last_name_2 TEXT NULL DEFAULT ''::TEXT,
  phone_number TEXT NULL,
  email_address TEXT NULL,
  phone_number_2 TEXT NULL,
  email_address_2 TEXT NULL,
  user_id UUID NOT NULL,
  CONSTRAINT Families_pkey PRIMARY KEY (id),
  CONSTRAINT Families_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users (id) ON DELETE CASCADE,
  CONSTRAINT family_name_length CHECK (
    (LENGTH(parent_guardian_first_name_1) >= 1)
    AND (LENGTH(parent_guardian_last_name_1) >= 1)
  )
) TABLESPACE pg_default;

CREATE TRIGGER free_tier_limit_families_trigger BEFORE INSERT ON "Families" FOR EACH ROW
EXECUTE FUNCTION free_tier_limit_trg ();
