CREATE TABLE public.Profiles (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  user_id UUID NULL,
  CONSTRAINT Profiles_pkey PRIMARY KEY (id),
  CONSTRAINT Profiles_user_id_key UNIQUE (user_id),
  CONSTRAINT Profiles_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users (id) ON DELETE CASCADE
) TABLESPACE pg_default;
