CREATE TABLE
  public.Students_All_Data (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    associated_family BIGINT NOT NULL,
    student_data BIGINT NULL,
    user_id UUID NOT NULL,
    CONSTRAINT Students_All_Data_pkey PRIMARY KEY (id),
    CONSTRAINT Students_All_Data_associated_family_fkey FOREIGN KEY (associated_family) REFERENCES "Families" (id) ON DELETE CASCADE,
    CONSTRAINT Students_All_Data_student_data_fkey FOREIGN KEY (student_data) REFERENCES "Students" (id) ON DELETE CASCADE,
    CONSTRAINT Students_All_Data_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users (id) ON DELETE CASCADE
  ) TABLESPACE pg_default;
