CREATE TABLE public.Students (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  first_name TEXT NOT NULL DEFAULT 'NOT NULL'::TEXT,
  last_name TEXT NOT NULL DEFAULT 'NOT NULL'::TEXT,
  phone_number TEXT NULL,
  email_address TEXT NULL,
  practice_log BIGINT NULL,
  rate TEXT NOT NULL,
  lesson_length TEXT NOT NULL DEFAULT ''::TEXT,
  rate_per_time TEXT NOT NULL DEFAULT 'per_hour'::TEXT,
  instrument TEXT NULL,
  skill_level TEXT NULL,
  gender TEXT NULL,
  age TEXT NULL,
  family_id BIGINT NOT NULL,
  user_id UUID NOT NULL,
  CONSTRAINT Students_pkey PRIMARY KEY (id),
  CONSTRAINT Students_family_id_fkey FOREIGN KEY (family_id) REFERENCES "Families" (id) ON DELETE CASCADE,
  CONSTRAINT Students_practice_log_fkey FOREIGN KEY (practice_log) REFERENCES "Practice_Log" (id) ON DELETE CASCADE,
  CONSTRAINT Students_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users (id) ON DELETE CASCADE,
  CONSTRAINT rate_not_empty_string CHECK ((LENGTH(rate) >= 1)),
  CONSTRAINT student_name_length CHECK (
    (LENGTH(first_name) >= 1)
    AND (LENGTH(last_name) >= 1)
  )
) TABLESPACE pg_default;

CREATE TRIGGER free_tier_limit_students_trigger
AFTER INSERT ON "Students"
FOR EACH ROW
EXECUTE FUNCTION free_tier_limit_trg ();
